const santosDoAno = {
    "01-01": "Solenidade de Maria Mãe de Deus (Theotokos); São Fulgêncio",
    "01-02": "Basílio Magno e Gregório Nazianzo, bispos e doutores da Igreja",
    "01-03": "Santa Genoveva, padroeira de Paris; Beata Estefânia Quinzani; São José Maria Tomasi",
    "01-04": "Santa Ângela de Folinho, religiosa Franciscana",
    "01-05": "São João Nepomuceno Neumann, bispo da Filadélfia",
    "01-06": "Santa Rafaela Maria do Sagrado Coração de Jesus",
    "01-07": "Beata Lindalva Justo de Oliveira, Mártir",
    "01-08": "São Severino",
    "01-09": "Santo André Corsini",
    "01-10": "Frei Gonçalo de Amarante, presbítero de Braga",
    "01-11": "Santo Higino, nono Papa da Igreja Católica",
    "01-12": "São Bernardo de Corleone",
    "01-13": "Hilário de Poitiers, bispo de doutor da Igreja",
    "01-14": "Santa Elisabete Ana Bayley Seton",
    "01-15": "Santo Amaro",
    "01-16": "Santo Honorato",
    "01-17": "Santo Antão, Abade",
    "01-18": "Santa Margarida da Hungria",
    "01-19": "São Canuto; São Germânico, mártir de Filadélfia",
    "01-20": "São Sebastião, mártir e São Fabião, papa e mártir",
    "01-21": "Santa Inês, virgem e mártir",
    "01-22": "São Vicente Pallotti; Beata Laura Vicuña",
    "01-23": "Santa Emerenciana, mártir romana; São Idelfonso, bispo de Toledo",
    "01-24": "São Francisco de Sales, bispo e doutor da Igreja",
    "01-25": "Conversão de São Paulo, Apóstolo; Santo Ananias",
    "01-26": "São Timóteo e São Tito, bispos",
    "01-27": "Ângela Meríci, virgem, fundadora das Ursulinas",
    "01-28": "São Tomás de Aquino, presbítero e doutor da Igreja",
    "01-29": "São Sulpício Severo",
    "01-30": "Santa Jacinta Mariscotti, virgem Romana",
    "01-31": "São João Bosco, presbítero",
    "02-01": "Beata Ludovica Albertoni, viúva Romana",
    "02-02": "Apresentação do Senhor; Nossa Senhora da Luz; Nossa Senhora dos Navegantes; Santa Domenica Mantovani",
    "02-03": "São Lourenço de Cantuária; São Brás de Sebaste; Santo Anscário (Oscar)",
    "02-04": "São João de Brito, presbítero e mártir",
    "02-05": "Santa Águeda, virgem e mártir",
    "02-06": "Santa Doroteia; São Paulo Miki e companheiros, mártires",
    "02-07": "Cinco Chagas do Senhor; Papa Pio IX",
    "02-08": "São Jerônimo Emiliano; Santa Josefina Bakhita, virgem",
    "02-09": "Santa Apolônia, virgem e mártir; Beata Anna Catharina Emmerick",
    "02-10": "Santa Escolástica, virgem",
    "02-11": "Nossa Senhora de Lourdes",
    "02-12": "Santa Eulália de Barcelona, virgem e mártir",
    "02-13": "São Martiniano",
    "02-14": "São Valentim; Santos Cirilo e Metódio",
    "02-15": "Santo Onésimo, Discípulo de São Paulo",
    "02-16": "Santa Juliana, virgem e mártir",
    "02-17": "Os Sete Santos Fundadores da Ordem dos Servos de Maria; Santa Engrácia de Braga",
    "02-18": "São Teotónio; Beato João de Fiesole (Fra Angélico)",
    "02-19": "São Conrado Confalonieri, eremita franciscano",
    "02-20": "São Francisco e Santa Jacinta Marto, pastorinhos de Fátima",
    "02-21": "São Pedro Damião, bispo e doutor da Igreja",
    "02-22": "Cátedra de São Pedro, Festa; Santa Margarida de Cortona",
    "02-23": "São Policarpo, bispo e mártir; Santa Josefina Vannini, Virgem",
    "02-24": "São Sérgio, monge eremita",
    "02-25": "Santos Luís Versiglia e Callisto Caravario",
    "02-26": "Santo Alexandre do Egito",
    "02-27": "São Gabriel de Nossa Senhora das Dores",
    "02-28": "São Romão, abade",
    "03-01": "São David, padroeiro do País de Gales; São Rosendo",
    "03-02": "Santa Inês da Boêmia (ou de Praga)",
    "03-03": "Santos Marino e Astério",
    "03-04": "São Casimiro",
    "03-05": "São João José da Cruz, Presbítero Franciscano",
    "03-06": "Santa Rosa de Viterbo",
    "03-07": "Santas Perpétua e Felicidade, mártires; Santa Teresa Margarida Redi, virgem",
    "03-08": "São João de Deus, religioso",
    "03-09": "Santa Francisca Romana, religiosa",
    "03-10": "Os Santos Mártires de Sebaste",
    "03-11": "São Eulógio, Sacerdote e mártir",
    "03-12": "Santo Inocêncio, Promotor da Paz",
    "03-13": "Santos Rodrigo e Salomão",
    "03-14": "Santa Matilde",
    "03-15": "São Longuinho; São Clemente Maria Hofbauer",
    "03-16": "Santa Eusébia",
    "03-17": "São Patrício, bispo",
    "03-18": "São Cirilo de Jerusalém, bispo e doutor da Igreja",
    "03-19": "São José, esposo da Virgem Maria",
    "03-20": "Santa Maria Josefina do Coração de Jesus Sancho de Guerra",
    "03-21": "São Nicolau de Flue, padroeiro da Suíça",
    "03-22": "São Zacarias, Papa; Santa Léia, viúva romana",
    "03-23": "São Toríbio de Mongrovejo, bispo",
    "03-24": "Santa Catarina da Suécia; Santo Oscar Romero",
    "03-25": "Solenidade da Anunciação do Senhor; São Dimas, o Bom Ladrão",
    "03-26": "São Bráulio",
    "03-27": "São Ruperto",
    "03-28": "São Guntrano; Santa Gisela da Baviera",
    "03-29": "São Constantino",
    "03-30": "São João Clímaco",
    "03-31": "Santa Balbina, virgem e mártir de Roma; São Benjamin",
    "04-01": "São Hugo de Grenoble",
    "04-02": "São Francisco de Paula, eremita",
    "04-03": "São Ricardo",
    "04-04": "Santo Isidoro, bispo e doutor da Igreja",
    "04-05": "São Vicente Ferrer, presbítero",
    "04-06": "São Marcelino",
    "04-07": "São João Batista de La Salle, presbítero",
    "04-08": "Santo Alberto",
    "04-09": "São Leopoldo Mandic e Santa Maria de Cleófas",
    "04-10": "Santa Madalena de Canossa",
    "04-11": "Santo Estanislau, bispo e mártir; Santa Gemma Galgani, virgem",
    "04-12": "São José Moscati médico de Nápoles; São Vitor",
    "04-13": "São Martinho I, Papa e mártir",
    "04-14": "Santa Ludovina",
    "04-15": "São Crescente",
    "04-16": "Santa Maria Bernadete Soubirous, virgem vidente de Lourdes",
    "04-17": "Santa Catarina Tekakwitha; Santo Aniceto",
    "04-18": "São Galdino, Santo Apolônio; Beata Maria da Encarnação",
    "04-19": "Santo Expedito; Santa Ema",
    "04-20": "Santa Inês de Montepulciano, virgem",
    "04-21": "Santo Anselmo, bispo e doutor da Igreja",
    "04-22": "São Caio, Papa; Santa Senhorinha",
    "04-23": "São Jorge, mártir",
    "04-24": "São Fidélis (Fiel) de Sigmaringa, presbítero e mártir",
    "04-25": "São Marcos evangelista",
    "04-26": "São Pascásio; Santo Anacleto",
    "04-27": "Santa Zita, virgem",
    "04-28": "Santa Gianna Beretta Molla; São Luí Maria Grignion de Montfort",
    "04-29": "Santa Catarina de Sena, virgem e doutora da Igreja",
    "04-30": "São Pio V, papa",
    "05-01": "São José Operário",
    "05-02": "Santo Atanásio, bispo e doutor da Igreja",
    "05-03": "São Filipe e São Tiago, Apóstolos",
    "05-04": "São Peregrino",
    "05-05": "Santo Ângelo",
    "05-06": "São Domingos Sávio",
    "05-07": "Santa Flávia Domitila",
    "05-08": "São Pedro de Tarantásia",
    "05-09": "São Pacómio, Abade; Santa Luiza de Marillac",
    "05-10": "Santo Antonino; São João de Ávila",
    "05-11": "Santo Inácio de Láconi",
    "05-12": "Santos Nereu, Aquiles e Pancrácio, mártires; Beata Imelda Lambertini, virgem",
    "05-13": "Nossa Senhora de Fátima",
    "05-14": "São Matias, apóstolo",
    "05-15": "Santa Dionísia; Santo Isidoro lavrador",
    "05-16": "São Simão Stock",
    "05-17": "São Pascoal Bailão",
    "05-18": "São João I, papa e mártir; São Leonardo Murialdo",
    "05-19": "Santa Maria Bernarda; Santo Ivo",
    "05-20": "São Bernardino de Sena, presbítero",
    "05-21": "São Cristóvão de Magalhães e companheiros mártires",
    "05-22": "Santa Rita de Cássia, viúva e religiosa Agostiniana",
    "05-23": "São João Batista de Rossi",
    "05-24": "Nossa Senhora Auxiliadora; São Vicente de Lérins",
    "05-25": "São Beda Venerável, doutor da Igreja; Santa Maria Madalena de Pazzi, virgem",
    "05-26": "São Filipe de Neri, presbítero",
    "05-27": "Santo Agostinho de Cantuária, bispo",
    "05-28": "São Germano, Bispo de Paris",
    "05-29": "Santa Ursula; São Maximino de Tréves; São Paulo VI, Papa",
    "05-30": "Santa Joana d’Arc, Virgem, padroeira da França",
    "05-31": "Visitação de Nossa Senhora, festa",
    "06-01": "São Justino, mártir",
    "06-02": "São Marcelino e São Pedro, mártires",
    "06-03": "São Carlos Lwanga e companheiros, mártires",
    "06-04": "São Francisco Caracciolo",
    "06-05": "São Bonifácio, bispo e mártir",
    "06-06": "São Norberto, bispo; São Marcelino Champagnat, presbítero",
    "06-07": "Santo Antônio Maria Gianelli",
    "06-08": "Santo Efrém, diácono e doutor da Igreja; Santa Maria do Divino Coração, religiosa",
    "06-09": "São José de Anchieta, sacerdote",
    "06-10": "Santo Anjo da Guarda de Portugal e Santa Olívia de Palermo, virgem e mártir",
    "06-11": "São Barnabé, apóstolo e Santa Paula Frassinetti",
    "06-12": "Santo Onofre",
    "06-13": "Santo António de Lisboa (Pádua), presbítero e doutor da Igreja",
    "06-14": "Santa Clotilde",
    "06-15": "Santa Germana Cousin, virgem; Beata Albertina Berkenbrock, virgem e mártir",
    "06-16": "São Ciro e Santa Julita, Mártires",
    "06-17": "São Ranério de Pisa",
    "06-18": "São Gregório de Barbarigo",
    "06-19": "São Romualdo, abade",
    "06-20": "Bem Aventuradas, Teresa, Mafalda e Sancha",
    "06-21": "São Luís Gonzaga",
    "06-22": "São João Fisher, bispo e mártir e São Tomás More, mártir",
    "06-23": "Santa Agripina; São José Cafasso",
    "06-24": "Solenidade do nascimento de João Batista",
    "06-25": "São Guilherme de Vercelli",
    "06-26": "São Josemaria Escrivá, sacerdote",
    "06-27": "Nossa Senhora do Perpétuo Socorro; São Cirilo de Alexandria, bispo e doutor da Igreja",
    "06-28": "Santo Irineu, bispo e mártir",
    "06-29": "São Pedro e São Paulo, Apóstolos",
    "06-30": "Protomártires da Igreja de Roma",
    "07-01": "Santo Aarão; Preciosíssimo Sangue de Jesus",
    "07-02": "São Bernardino Realino",
    "07-03": "São Tomé, apóstolo",
    "07-04": "Santa Isabel Rainha de Portugal",
    "07-05": "Santo Antonio Maria Zaccaria, presbítero",
    "07-06": "Santa Maria Goretti, virgem e mártir",
    "07-07": "São Vilibaldo; Beata Maria Romero Meneses; Bem-aventurado Bento XI, papa",
    "07-08": "Papa Eugênio III; Santos Áquila e Priscila, discípulos de São Paulo",
    "07-09": "Santa Paulina do Coração Agonizante de Jesus; Santa Verônica Giuliani",
    "07-10": "Santo Olavo, rei da Noruega",
    "07-11": "São Bento, abade",
    "07-12": "São João Gualberto; São Luiz e Santa Zélia, pais de santa Teresinha",
    "07-13": "São Henrique e Santa Cunegundes; Santa Teresa de Jesus dos Andes; Nossa Senhora da Rosa Mística",
    "07-14": "São Camilo de Lellis, presbítero",
    "07-15": "São Boaventura, bispo e doutor da Igreja",
    "07-16": "Nossa Senhora do Carmo, memória",
    "07-17": "Santa Marcelina, virgem; Santo Inácio de Azevedo; Mártires Carmelitas de Compiègne",
    "07-18": "São Francisco Solano; Santo Agapito, mártir",
    "07-19": "Beatas Francisca do Coração de Jesus Aldea Araujo e Rita Dolores do Coração de Jesus Pujalte Sánchez",
    "07-20": "Santa Margarida de Antioquia, virgem e mártir; Santo Aurélio",
    "07-21": "São Lourenço de Brandis, presbítero e doutor da Igreja",
    "07-22": "Santa Maria Madalena, discípula de Cristo",
    "07-23": "Santa Brígida, religiosa",
    "07-24": "Santa Cristina, virgem e mártir",
    "07-25": "São Cristóvão; São Tiago Maior, apóstolo",
    "07-26": "São Joaquim e Santa Ana, pais de Nossa Senhora",
    "07-27": "São Pantaleão, médico mártir",
    "07-28": "Santo Inocêncio; São Celestino",
    "07-29": "Santa Marta",
    "07-30": "São Pedro Crisólogo, bispo e doutor da Igreja; Santa Maria de Jesus Sacramento Venegas",
    "07-31": "Santo Inácio de Loyola, presbítero e fundador da Companhia de Jesus",
    "08-01": "Santo Afonso Maria de Ligório, bispo e doutor da Igreja",
    "08-02": "São Pedro Julião Eymard, o Apóstolo da Eucaristia",
    "08-03": "Santa Lídia, discípula de São Paulo",
    "08-04": "São João Maria Vianney (Cura d’Ars)",
    "08-05": "Dedicação da Basílica de Santa Maria Maior",
    "08-06": "Festa da Transfiguração do Senhor",
    "08-07": "Sisto II, papa, e companheiros, mártires",
    "08-08": "São Domingos de Gusmão, presbítero",
    "08-09": "Santa Teresa Benedita da Cruz (Edith Stein), virgem e mártir",
    "08-10": "São Lourenço, diácono e mártir e Santa Filomena, virgem e mártir",
    "08-11": "Santa Clara de Assis, virgem e Santa Suzana, virgem e mártir",
    "08-12": "Santa Joana Francisca de Chantal",
    "08-13": "Santos Ponciano e Hipólito, mártires; Santa Dulce dos Pobres",
    "08-14": "Maximiliano Maria Kolbe, presbítero e mártir",
    "08-15": "Solenidade da Assunção da Virgem Maria; São Tarcísio, mártir da Eucaristia",
    "08-16": "São Estevão, Rei da Hungria",
    "08-17": "São Jacinto",
    "08-18": "Santa Helena, imperatriz",
    "08-19": "São João Eudes, presbítero",
    "08-20": "São Bernardo Claraval, abade e doutor da Igreja",
    "08-21": "São Pio X, papa",
    "08-22": "Nossa Senhora Rainha",
    "08-23": "Santa Rosa de Lima, virgem, padroeira da América Latina",
    "08-24": "São Bartolomeu, apóstolo",
    "08-25": "São Luis XI, Rei da França; Santa Maria de Jesus Crucificado, monja carmelita",
    "08-26": "São Zeferino, Papa e mártir",
    "08-27": "Santa Mônica, Mãe de Santo Agostinho",
    "08-28": "Santo Agostinho, bispo e doutor da Igreja",
    "08-29": "Martírio de São João Batista",
    "08-30": "São Cesário de Arles; Santos Félix e Adauto, Mártires",
    "08-31": "São Raimundo Nonato",
    "09-01": "Beatriz da Silva, virgem Fundadora das Monjas Concepcionistas",
    "09-02": "Santa Doroteia, virgem e mártir de Cesareia",
    "09-03": "São Gregório Magno",
    "09-04": "Santa Rosália",
    "09-05": "Santa Madre Teresa de Calcutá; São Lourenço Justiniano Primeiro Patriarca de Veneza",
    "09-06": "São Liberato de Loro",
    "09-07": "Santa Regina, virgem e mártir",
    "09-08": "Festa da Natividade de Maria",
    "09-09": "São Pedro Claver",
    "09-10": "São Nicolau de Tolentino",
    "09-11": "São João Gabriel Perboyre",
    "09-12": "São Guido de Anderlecht; Santíssimo nome de Maria",
    "09-13": "João Crisóstomo, bispo e doutor da Igreja",
    "09-14": "Exaltação da Santa Cruz",
    "09-15": "Nossa Senhora das Dores",
    "09-16": "São Cornélio, papa e São Cipriano bispo, mártires",
    "09-17": "Roberto Belarmino, bispo e doutor da Igreja",
    "09-18": "São José de Cupertino",
    "09-19": "São Januário, bispo e doutor da Igreja; Nossa Senhora da Salette",
    "09-20": "Santo André Kim Taegon e companheiros mártires",
    "09-21": "São Mateus, apóstolo e evangelista",
    "09-22": "São Maurício e companheiros mártires",
    "09-23": "São Pio de Pietrelcina",
    "09-24": "Nossa Senhora das Mercês; São Gerardo Sagredo",
    "09-25": "São Cléofas; São Firmino",
    "09-26": "São Cosme e Damião, mártires",
    "09-27": "Vicente de Paulo, presbítero fundador das filhas da caridade",
    "09-28": "São Venceslau, duque e mártir",
    "09-29": "São Miguel, São Gabriel, São Rafael, Arcanjos",
    "09-30": "São Jerônimo, presbítero e doutor da Igreja",
    "10-01": "Santa Teresinha do Menino Jesus, virgem e doutora da Igreja",
    "10-02": "Santos Anjos da Guarda, memória",
    "10-03": "Protomártires do Brasil",
    "10-04": "São Francisco de Assis",
    "10-05": "Santa Faustina Kowalska, apóstola da Divina Misericórdia",
    "10-06": "São Bruno, presbítero",
    "10-07": "Nossa Senhora do Rosário",
    "10-08": "Santa Pelágia, virgem e mártir",
    "10-09": "São Dionísio e seus companheiros mártires; São João Leonardo",
    "10-10": "São Daniel Comboni",
    "10-11": "São João XXIII, papa",
    "10-12": "Nossa Senhora Aparecida; Beato Carlo Acutis",
    "10-13": "Beata Alexandrina Maria da Costa, virgem; Santo Eduardo",
    "10-14": "São Calisto I",
    "10-15": "Santa Teresa de Jesus (Teresa d’Ávilla), reformadora do carmelo, virgem e doutora da Igreja",
    "10-16": "Santa Edwiges, padroeira dos endividados; Santa Margarida Maria Alacoque; São Geraldo Majela",
    "10-17": "Santo Inácio de Antioquia",
    "10-18": "São Lucas, evangelista, médico",
    "10-19": "São Paulo da Cruz, presbítero; São Pedro de Alcântara",
    "10-20": "Santa Maria Bertilla Boscardin",
    "10-21": "Santa Úrsula e companheiras mártires",
    "10-22": "São João Paulo II, papa",
    "10-23": "João de Capistrano, presbítero",
    "10-24": "Antônio Maria Claret, bispo; Benigna, a pequena mártir brasileira",
    "10-25": "Santo Antônio de Sant’Ana Galvão (Frei Galvão)",
    "10-26": "Santo Evaristo",
    "10-27": "São Gonçalo de Lagos, presbítero",
    "10-28": "São Simão e São Judas Tadeu, Apóstolos",
    "10-29": "São Narciso",
    "10-30": "São Frumêncio; São Germano",
    "10-31": "Santo Afonso Rodrigues",
    "11-01": "Solenidade de Todos os Santos",
    "11-02": "Comemoração de Todos os Fiéis Defuntos",
    "11-03": "Martinho de Porres (ou de Lima), religioso",
    "11-04": "Carlos Borromeu, bispo",
    "11-05": "São Zacarias e Santa Isabel",
    "11-06": "São Leonardo de Noblac e São Nuno de Santa Maria",
    "11-07": "São Vilibrordo",
    "11-08": "São Deodato",
    "11-09": "Dedicação da Basílica de São João de Latrão",
    "11-10": "São Leão Magno, papa e doutor da Igreja",
    "11-11": "São Martinho, bispo",
    "11-12": "São Josafá, bispo e mártir",
    "11-13": "Santo Estanislau Kostka",
    "11-14": "São José Pignatelli",
    "11-15": "Alberto Magno, bispo e doutor da Igreja",
    "11-16": "Santa Margarida Rainha da Escócia; Santa Gertrudes; Santa Inês de Assis",
    "11-17": "Santa Isabel da Hungria, princesa, viúva e religiosa",
    "11-18": "Dedicação das Basílicas de São Pedro e São Paulo, Apóstolos",
    "11-19": "São Roque González e companheiros mártires",
    "11-20": "São Félix de Valóis; São Edmundo",
    "11-21": "Apresentação de Nossa Senhora ao templo",
    "11-22": "Santa Cecília, virgem e mártir, padroeira dos músicos",
    "11-23": "São Clemente I, papa e mártir, e São Columbano, Abade",
    "11-24": "Santo André Dung-Lac e companheiros, mártires",
    "11-25": "Santa Catarina de Alexandria, Virgem e Mártir",
    "11-26": "São Leonardo de Porto Maurício, padroeiro dos sacerdotes missionários",
    "11-27": "Nossa Senhora das Graças e Medalha Milagrosa",
    "11-28": "Santa Catarina Labouré, vidente de Nossa Senhora das Graças",
    "11-29": "São Saturnino, mártir; São Francisco Antônio Fasani",
    "11-30": "Santo André, Apóstolo",
    "12-01": "Santo Elígio (ou Elói), Bispo",
    "12-02": "São Silvério, Papa",
    "12-03": "São Francisco Xavier, Presbítero",
    "12-04": "João Damasceno, Presbítero e Doutor, Santa Bárbara Mártir",
    "12-05": "São Sabas, Abade; São Martinho de Dumes",
    "12-06": "São Nicolau de Mira, Bispo",
    "12-07": "Santo Martinho de Dume",
    "12-08": "Solenidade da Imaculada Conceição da Virgem Maria",
    "12-09": "São Juan Diego",
    "12-10": "São João Roberts; São Melquíades",
    "12-11": "São Dâmaso I, Papa",
    "12-12": "Nossa Senhora de Guadalupe, padroeira principal da América Latina",
    "12-13": "Santa Luzia, Virgem e Mártir",
    "12-14": "São João da Cruz, Presbítero e Doutor da Igreja",
    "12-15": "Santa Cristiana; Beata Maria Vitória de Fornari Strata",
    "12-16": "Santa Adelaide",
    "12-17": "São Lázaro de Betânia; Santa Olímpia",
    "12-18": "São Gaciano; Nossa Senhora do Ó",
    "12-19": "Santo Urbano V",
    "12-20": "São Domingos de Silos",
    "12-21": "Pedro Canísio, Presbítero e Doutor da Igreja",
    "12-22": "Francisca Xavier Cabríni",
    "12-23": "São João Câncio, Presbítero",
    "12-24": "São Charbel, Presbítero; Santa Tarsila",
    "12-25": "Solenidade do Natal do Senhor",
    "12-26": "Santo Estêvão, Primeiro Mártir",
    "12-27": "São João, Apóstolo e Evangelista",
    "12-28": "Santos Inocentes, Mártires",
    "12-29": "Tomás Becket, Bispo e Mártir",
    "12-30": "São Rugero; Beata Margarida Colonna",
    "12-31": "Silvestre I, Papa"
};